[package]
name = "emeli"
version = "0.1.0"
edition = "2021"
description = "Emeli-mail desktop shell"
authors = ["igor-ganov"]
license = "MIT"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
keyring = { version = "3", features = ["windows-native", "apple-native", "sync-secret-service"] }

[profile.release]
opt-level = "s"
lto = true
